## Transform  
This notebook contains a set NYC datasets taken from OpenNYC (https://opendata.cityofnewyork.us/), New York's Open Data Portal. For each dataset
- Read in the data
- Inspect the data looking for any issues
- Construct Python code to answer the accompanying questions

## NYPD Demographics
- How many rows and columns are in this data? 
- What are the variable types of each column? 
- Are any columns missing values? 
- What % of NYPD employees are female?
- How is Gender different from sex? 
- What are the mean, median and mode number of years on job? 
- Now, examine Gender distribution by Rank? 
- Now, examine Race distribution by Rank? 

Source: https://data.cityofnewyork.us/Public-Safety/NYPD-Personnel-Demographics/5vr7-5fki/about_data

In [56]:
import pandas as pd
nypd = pd.read_csv('nypd_demographics.csv')
nypd.head()

,Gender,Race,MOS_Type,ranklit,sex,appdate,YearsOnJob,YearsOnJob (bins)
0,Male,Hispanic,Uniform,Police Officer,Male,12/17/2025,0,0
1,Male,Hispanic,Uniform,Police Officer,Male,12/17/2025,0,0
2,Male,Hispanic,Uniform,Police Officer,Male,12/17/2025,0,0
3,Male,Hispanic,Uniform,Police Officer,Male,12/17/2025,0,0
4,Male,Hispanic,Uniform,Police Officer,Male,12/17/2025,0,0

## New York Payroll
NYC Payroll Data of those who had a Base Salary greater than $100,000 in 2025.
https://data.cityofnewyork.us/City-Government/Citywide-Payroll-Data-Fiscal-Year-/k397-673e/explore/query/SELECT%0A%20%20%60fiscal_year%60%2C%0A%20%20%60payroll_number%60%2C%0A%20%20%60agency_name%60%2C%0A%20%20%60last_name%60%2C%0A%20%20%60first_name%60%2C%0A%20%20%60mid_init%60%2C%0A%20%20%60agency_start_date%60%2C%0A%20%20%60work_location_borough%60%2C%0A%20%20%60title_description%60%2C%0A%20%20%60leave_status_as_of_june_30%60%2C%0A%20%20%60base_salary%60%2C%0A%20%20%60pay_basis%60%2C%0A%20%20%60regular_hours%60%2C%0A%20%20%60regular_gross_paid%60%2C%0A%20%20%60ot_hours%60%2C%0A%20%20%60total_ot_paid%60%2C%0A%20%20%60total_other_pay%60%0AWHERE%20%60fiscal_year%60%20IN%20%28%222025%22%29%20AND%20%28%60base_salary%60%20%3E%20200000%29%0AORDER%20BY%20%60agency_name%60%20ASC%20NULL%20LAST%2C%20%60fiscal_year%60%20DESC%20NULL%20FIRST/page/filter


- Who are the top 10 earners?
- Which agency pays the most? 
- How much does someone with "Data" in their Title earn? 
- How many Machine Learning Engineers are employed (and earn more than 100K)?

In [79]:
payroll = pd.read_csv('nyc_payroll_200k_plus.csv')
#payroll = pd.read_csv('nyc_payroll_100k_plus.csv')
payroll.head()

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay
0,2025,67,ADMIN FOR CHILDREN'S SVCS,WADDY,WALTIA,S,01/03/2012,MANHATTAN,ADMINISTRATIVE DIRECTOR OF SOCIAL SERVICES,ACTIVE,"$244,039.00",per Annum,"1,820","$235,682.95",0.0,$0.00,$0.00
1,2025,67,ADMIN FOR CHILDREN'S SVCS,KRAUSS,JILL,A,02/06/2012,MANHATTAN,ADMINISTRATIVE MANAGER,ACTIVE,"$263,497.00",per Annum,"1,820","$254,475.20",0.0,$0.00,"$1,500.00"
2,2025,67,ADMIN FOR CHILDREN'S SVCS,NEIDIG,JUSTIN,M,11/26/2012,MANHATTAN,EXECUTIVE AGENCY COUNSEL,ACTIVE,"$203,623.00",per Annum,"1,820","$196,651.48",0.0,$0.00,$0.00
3,2025,67,ADMIN FOR CHILDREN'S SVCS,WHITE,ANDREW,K,06/23/2014,MANHATTAN,ADMINISTRATIVE DIRECTOR OF SOCIAL SERVICES,ACTIVE,"$273,442.00",per Annum,"1,820","$264,079.57",0.0,$0.00,$0.00
4,2025,67,ADMIN FOR CHILDREN'S SVCS,FREEDMAN,NEIL,S,12/08/2014,MANHATTAN,ADMINISTRATIVE DIRECTOR OF SOCIAL SERVICES,ACTIVE,"$202,240.00",per Annum,"1,820","$195,315.47",0.0,$0.00,$0.00

## Baby Names

- Which is the most common baby name?
- Compare by gender.
- Compare by ethnicity.
- Trend over time.

https://data.cityofnewyork.us/Health/Popular-Baby-Names/25th-nujf/about_data

In [130]:
baby = pd.read_csv('nyc_babies.csv', skiprows = 1, names= ['year','gender','ethnicity','name','count','rank'])
baby.head()

   year  gender                   ethnicity    name  count  rank
0  2021  FEMALE  ASIAN AND PACIFIC ISLANDER  Olivia     71     1
1  2021  FEMALE  ASIAN AND PACIFIC ISLANDER   Chloe     71     1
2  2021  FEMALE  ASIAN AND PACIFIC ISLANDER    Emma     66     2
3  2021  FEMALE  ASIAN AND PACIFIC ISLANDER     Mia     59     3
4  2021  FEMALE  ASIAN AND PACIFIC ISLANDER     Ava     53     4

In [131]:
#import seaborn as sns
#sns.lineplot(data = baby.loc[baby.name.isin(['Emma','Olivia','Sophia']),:], x = 'year', y = 'count', hue = 'name',errorbar = None );

## NYC Dog Licensing  
Which is the most popular dog breed? May have make names consistent
Most popular dog names? 
Median age when a dog is issued a license? 

Source: https://data.cityofnewyork.us/Health/NYC-Dog-Licensing-Dataset/nu7n-tubp/about_data

In [133]:
import pandas as pd
dogs = pd.read_csv('dog_licenses.csv', parse_dates=['LicenseIssuedDate','LicenseExpiredDate'] )
dogs.head()
#dogs.AnimalBirthYear = pd.to_datetime(dogs.AnimalBirthYear,format = '%Y', errors = 'coerce')
#dogs.AnimalBirthYear.dt.year

C:\Users\vlala\AppData\Local\Temp\ipykernel_23876\130868812.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  dogs = pd.read_csv('dog_licenses.csv', parse_dates=['LicenseIssuedDate','LicenseExpiredDate'] )

BreedName
Unknown                        63558
Yorkshire Terrier              40224
Shih Tzu                       37108
Chihuahua                      28086
Labrador Retriever             21852
                               ...
Pinscher Mix                       1
Mixed breed                        1
YORKER/JACKRUSELL/CHIHUAHUA        1
DACHSHUND   X                      1
FOX TER/C.SPAN                     1
Name: count, Length: 1595, dtype: int64

## Wifi Hotspots

- Which borough has the most Wi-Fi hotspots?
- Which provider operates the most hotspots?
- Are hotspots mostly outdoor, subway, library, or public-space locations?
- Which ZIP codes have the most hotspots?
- How many hotspots are free versus limited free?



Source: https://data.cityofnewyork.us/City-Government/NYC-Wi-Fi-Hotspot-Locations/yjub-udmw/about_data

In [6]:
wifi = pd.read_csv('wifi.csv')
wifi.head()

,OBJECTID,Borough,Type,Provider,Name,Location,Latitude,Longitude,X,Y,...,Neighborhood Tabulation Area (NTA),Council Distrcit,Postcode,BoroCD,Census Tract,BCTCB2010,BIN,BBL,DOITT_ID,"Location (Lat, Long)"
0,10604,4,Limited Free,SPECTRUM,Baisley Pond Park,Park Perimeter,40.674860,-73.784120,"1,044,131.89696","185,219.892077",...,Springfield Gardens North,28,11434,412,294,294,0,0,1408,"(40.6748599999, -73.7841200005)"
1,10555,4,Limited Free,SPECTRUM,Kissena Park,Park Perimeter,40.747560,-73.818150,"1,034,637.51076","211,685.217755",...,Flushing,20,11355,407,845,845,0,0,1359,"(40.7475599996, -73.8181499997)"
2,12370,3,Free,Transit Wireless,Grand St (L),Grand St (L),40.711926,-73.940670,"1,000,698.12752","198,655.90884",...,East Williamsburg,34,11206,301,495,495,0,0,1699,"(40.7119259997, -73.9406699994)"
3,9893,3,Free,Downtown Brooklyn,NaN,125 Court St.,40.689985,-73.991995,"986,469.966349","190,656.680416",...,Brooklyn Heights-Cobble Hill,33,11201,302,9,9,3388736,3002777501,298,"(40.6899850001, -73.9919950004)"
4,10169,1,Free,Transit Wireless,Lexington Av-63 St (F),Lexington Av-63 St (F),40.764630,-73.966115,"993,636.552081","217,853.888161",...,Upper East Side-Carnegie Hill,4,10065,108,120,120,0,0,599,"(40.7646300002, -73.9661150001)"

### NYC Restaurants
Department of Health data on New York restaurant inspections recorded between Jan 1, 2025 and June 10, 2026

- What are the most common cuisine types in NYC?
- Which borough has the most restaurants in the dataset?
- What is the distribution of inspection scores?
- Which cuisine types have the highest average inspection scores?
- How many restaurants receive A, B, or C grades?
- What are the most common violation types?

Source: https://data.cityofnewyork.us/Health/DOHMH-New-York-City-Restaurant-Inspection-Results/43nn-pn8j/about_data

In [147]:
restaurants = pd.read_csv('restaurants_jan_jun_2026.csv')
restaurants.head()

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,...,INSPECTION TYPE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA,Location
0,50177166,CARIBBEAN FLAME CUISINE,Queens,126-08,111 AVENUE,11420.0,3479897451,Caribbean,04/16/2026,Establishment re-opened by DOHMH.,...,Pre-permit (Operational) / Reopening Inspection,40.682290,-73.814977,410.0,28.0,17200.0,4250742.0,4.116310e+09,QN55,POINT (-73.814976545822 40.682290067686)
1,50090528,16 HANDLES,Manhattan,428,3 AVENUE,10016.0,2122131755,Frozen Desserts,04/30/2026,No violations were recorded at the time of thi...,...,Administrative Miscellaneous / Initial Inspection,40.743050,-73.980083,106.0,2.0,7200.0,1018264.0,1.008850e+09,MN20,POINT (-73.980083041804 40.743050400951)
2,50148121,OLD SPORT FOOD,Queens,67-03,AUSTIN STREET,11375.0,9292960009,Chinese,04/23/2026,Violations were cited in the following area(s).,...,Cycle Inspection / Re-inspection,40.724039,-73.855390,406.0,29.0,71306.0,4075085.0,4.031680e+09,QN17,POINT (-73.855389894931 40.724038560107)
3,41640282,GYU-KAKU,Manhattan,321,WEST 44 STREET,10036.0,6466929115,Japanese,04/27/2026,Violations were cited in the following area(s).,...,Cycle Inspection / Initial Inspection,40.758883,-73.989669,104.0,3.0,12100.0,1080878.0,1.010350e+09,MN15,POINT (-73.989669154574 40.758883444152)
4,50167382,EXPRESS MANTI,Brooklyn,1013,AVENUE H,11230.0,3479253178,Eastern European,01/21/2026,Violations were cited in the following area(s).,...,Pre-permit (Operational) / Initial Inspection,40.629460,-73.966841,314.0,45.0,46000.0,3170245.0,3.064980e+09,BK42,POINT (-73.966841370368 40.629460358704)